/// Flutter icons EcommerceIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EcommerceIcons
///      fonts:
///       - asset: fonts/EcommerceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EcommerceIcons {
  EcommerceIcons._();

  static const _kFontFam = 'EcommerceIcons';
  static const _kFontPkg = null;

  static const IconData hours24 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplane = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atm = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balance = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_1 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData browser = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator_1 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_machine = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_1 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_2 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_service = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hanger = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invoice = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_store = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_method = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percentage = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData placeholder = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purse = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shirt = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trolley = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_1 = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voucher = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_1 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
